### ISSUE TITLE
Importing multiple csv's into DataFrame fails with null values

### ISSUE THREAD

**Issue by ethanwhite** [ContinuumIO/into#84]
In 0.2.1, importing multiple csv's, at least one of which has null values, results in errors.

### One csv has null vaules in a column and another doesn't

Error:
`Exception: Integer column has NA values`

Example:

examp1.csv:
```
a,b,c
1,2,3
4,5,6
7,8,9
```

examp2.csv:
```
a,b,c
1,2,3
4,,6
7,8,9
```

examp.py
```
into(pd.DataFrame, 'examp*.csv')
``` 

### Multiple csv's have null values in the same column

Error:
`ValueError: cannot convert float NaN to integer`

Example:

examp1.csv:
```
a,b,c
1,2,3
4,,6
7,8,9
```

examp2.csv:
```
a,b,c
1,,2
3,4,5
6,7,8
```

examp.py
```
into(pd.DataFrame, 'examp*.csv')
```

In both of these cases importing the csv's one at a time works fine.

**Comment by mrocklin** [comment]
The problem here is that we have to guess the data type to use after looking at only the beginning of the first CSV file.  If there are no missing values in an integer column then we assume that the dtype should be `int`.  If, later on, we find that we were wrong then we fail; we should have chosen a `float` dtype so that Pandas could represent missing values.

So what should we do in this case?  Should we read through the entire dataset once to determine dtype and then again to load?  Should we require extra input from the user on what the dtypes should be?  Suggestions?

**Comment by cpcloud** [comment]
Isn't the second case a bug? Both csvs in that case should should be float for that column. Are we not discovering enough lines?

**Comment by mrocklin** [comment]
The second case works ok for me.

```Python
In [1]: !head example1.csv
a,b,c
1,2,3
4,,6
7,8,9

In [2]: !head example2.csv 
a,b,c
1,,2
3,4,5
6,7,8

In [3]: from into import *

In [4]: into(pd.DataFrame, 'example*.csv')
Out[4]: 
   a   b  c
0  1   2  3
1  4 NaN  6
2  7   8  9
3  1 NaN  2
4  3   4  5
5  6   7  8
```

**Comment by ethanwhite** [comment]
I can confirm that make second case is a bad report (it works fine on my work computer. Sorry.

**Comment by ethanwhite** [comment]
> So what should we do in this case? Should we read through the entire dataset once to determine dtype and then again to load? Should we require extra input from the user on what the dtypes should be? Suggestions?

Reading the entire file is an option for smallish data, but could become prohibitive for larger datasets. I would be happy to have the option to provide dtype input for this sort of case, though I think many scientists will find it unintuitive that that have to specify a float dtype to handle nulls in an integer column.

When I do this in Pandas it handles it behind the scenes (I'm not sure how). E.g.,

```python
In [1]: %paste
import pandas as pd
datafiles = ['examp1.csv', 'examp2.csv']
data = pd.DataFrame()
for datafile in datafiles:
    new_data = pd.read_csv(datafile)
    data = data.append(new_data, ignore_index=True)
data
## -- End pasted text --
Out[1]: 
   a   b  c
0  1   2  3
1  4   5  6
2  7   8  9
3  1 NaN  2
4  3   4  5
5  6   7  8

In [2]: type(data['b'][0])
Out[2]: numpy.float64

In [3]: type(data['a'][0])
Out[3]: numpy.int64
```

**Comment by mrocklin** [comment]
I believe that they mutate the underlying dataframe to the new type.  This would be possible for us to do with dataframes as well (with some elbow grease) but wouldn't be possible to do generally because many target formats don't support dtype mutation.

My general solution to this problem is to supply a datashape.  I should write a clear document on how this works.  The best thing I have now is [part of the blaze tutorial](http://nbviewer.ipython.org/github/mrocklin/blaze-tutorial/blob/master/02-into-Datatypes.ipynb), particularly the section that begins "Tweaking Datashapes for Performance"

**Comment by ethanwhite** [comment]
Ah, yes, this

> ds = dshape('var * {lat: float64, long: float64}')
> into(pd.DataFrame, data, dshape=ds)

looks like a perfectly good solution to me.

Time allowing, having an optional argument that asks `into` to fully read through all of the files to determine the data types robustly would be a nice convenience (when the data isn't too large).

**Comment by mrocklin** [comment]
Quick docs on using datashape with into.  Feedback to make this more clear is very welcome.

http://into.readthedocs.org/en/latest/datashape.html

Optional arguments to fully read files are doable for many particular formats.  It would be hard to do this across everything though.  There isn't a single place where `into` says "open files".  This is where the distributed nature of `into` hurts us; it's hard to reliably enforce conventions.

Going to close this issue for now.

**Comment by ethanwhite** [comment]
Looks great! Thanks.
